### PR TITLE
Added support for IPv6 / AAAA records and updated base code

### PR DESCRIPTION
**Pull request by Wizman87**
As described in the title. In addition, IPv4 and IPv6 regular expressions, code formatting, and descriptive comments have all been cleaned up and updated. Please feel free to contribute feedback on these changes, review the commits, and personally add any finishing touches or edits to the pull request. Lastly, if any of the commits are unneeded or instead should be migrated to an issue, please let me know! It's certainly possible that some or all of the new code written here can be integrated into the main branch. Thank you!

### CODE REVIEW

**Comment by ndrone-kr** [comment]
Nice work! I also like that you expanded the comments to make them more clear. Question is it worth setting a block to see if the ipv4 is valid before checking ipv6? Do we need create/update records for both versions? And a follow up can we just set one ip variable to be used throughout the rest of the script instead of checking both ip variables throughout?

**Comment by Wizman87** [comment]
Absolutely! I can clarify a few things on that. First for setting a block to see if the IPv4 is valid before checking IPv6, I am doing this in order to allow the script to continue running even if an IPv4 address or an IPv6 address is not pulled from a website. This may or may not be the best way to do that, though that is what I've done here. There may be a cleaner method than what I wrote to accomplish the same goal, though as a disclaimer, I am fairly new to bash scripting. To continue, to answer your second question regarding creating and updating records for both versions, as that's already what the script is accomplishing with the A records, I've simply added on to that by extending out the same functionality to the AAAA records as well. Finally, for setting one IP variable to be used throughout the rest of the script instead of checking both IP variables thoughout the script, I'm unsure what you mean. Can you clarify which variables you're referring to? As both the IPv4 (A record) and IPv6 (AAAA record) utilize different regular expressions and IP addressing formats, I feel it's best to keep them separated? Are you referring to the validity checks used for exiting the script after each GET or PULL section? I included these checks to ensure the script exited before executing additional checks and calls to CloudFlare. Thanks, ndrone-kr!

**Comment by Wizman87** [comment]
To add on to my previous comment, it certainly would've been possible (and easier) to keep the code separated between two different bash scripts. As in, one script for IPv4 (A records) and another for IPv6 (AAAA records). However, I felt it would be more preferred to include both, as having only a singular script performing the job of two is often the more preferred option by users. In addition, IPv6 is quickly becoming the standard while IPv4 is slowly being phased out during this transition phase. In my honest opinion, it makes a lot more sense to integrate and utilize IPv6 addressing at some point or another while moving forward. With that said though, I can certainly understand the different use cases and alternative option of utilizing two scripts instead of one that other users may prefer to choose to utilize.

**Comment by ndrone** [comment]
Honestly I don't know the correct course of action. Honestly they were just questions that popped into my head while reviewing your code. I do like the idea of separate scripts or one main script that then loads functions in from a separate file. So one file contains the IPv4 functions, and a second file contains the IPv6 functions. Then the main script takes a flag of which version of IP addresses you are using. Don't feel like have to make changes based on what I stated. I'm not the owner of this repository. I'm just brain dumping what comes out of my head.

```
# pseudo code
if [ ipv4_flag == true ] then
  source ./ipv4_functions.sh
else
  source ./ipv6_functions.sh
end if
```

**Comment by Wizman87** [comment]
Those were some good questions! I also appreciate the idea of having additional options available to users through the usage of separate scripts and loading of functions from separate files for the sake of modularity. Though having said that, I personally prefer the inclusion of both types of IP addressing within a singular script. I am also unsure if either of those options would be the desired outcome of the owner of this repository there there to be a split or inclusion of separate files. I will await additional comments from him. In the meantime, I will keep my fork repository open for now as other like-minded users have done as well.

**Pull request closed without merging**
